import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./contexts/AuthContext";
import AuthInitializer from "./utils/AuthInitializer";
import TopNav from "./components/TopNav";
import BottomNav from "./components/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`min-h-screen w-full mx-auto max-w-lg overflow-hidden border-[1px] rounded-2xl shadow-lg ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AuthInitializer />
          <TopNav />
          <main className="overflow-y-auto h-[calc(100vh-1.5rem-1.75rem)]">
            {children}
          </main>
          <BottomNav />
        </AuthProvider>
      </body>
    </html>
  );
}